import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import { test } from 'node:test';
import ts from 'typescript';
function load(path, require) { const exports = {}; new Function('require','exports', ts.transpileModule(readFileSync(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(require,exports); return exports; }
const months = load('../lib/dashboard-month.ts',()=>{});
test('Bangkok previous month, year rollover, leap month and future dates',()=>{
 assert.equal(months.previousBangkokMonth(new Date('2026-09-30T18:00:00Z')),'2026-09');
 assert.equal(months.previousBangkokMonth(new Date('2026-01-02T00:00:00Z')),'2025-12');
 assert.equal(months.monthRange('2024-02',new Date('2026-10-01')).dates.length,29);
 assert.equal(months.monthRange('2026-10',new Date('2026-10-02T00:00:00Z')).dates.length,2);
 assert.equal(months.monthRange('2027-01',new Date('2026-10-02')).dates.length,0);
 assert.throws(()=>months.monthRange('2026-13'));
 const e={id:'A',start_date:'02/09/2026',end_date:'03/09/2026',status:'ลาออก',position:'Staff',employment:'FullTime'};
 assert.equal(months.requiresWorkReview(e,'2026-09-01',[],['working']),false);
 assert.equal(months.requiresWorkReview(e,'2026-09-04',[],['working']),false);
 const absence=[{employee_id:'A',record_date:'2026-09-02',record_type:'absence',source_type:'manual'}];
 assert.equal(months.requiresWorkReview(e,'2026-09-02',absence,['working']),false);
 assert.equal(months.requiresWorkReview(e,'2026-09-02',absence,['absence']),true);
 assert.equal(months.requiresWorkReview(e,'2026-09-02',[{...absence[0],source_type:'work_audit'}],['working']),true);
 assert.equal(months.requiresWorkReview({...e,position:'Part-Time'},'2026-09-02',[],['working']),false);
});
test('monthly SQL summaries respect permissions, ownership and actual saved totals', async()=>{
 const sqlite = new DatabaseSync(':memory:');
 sqlite.exec(`CREATE TABLE hr_employees(id TEXT,nickname TEXT,team TEXT,position TEXT,employment TEXT,status TEXT,start_date TEXT,end_date TEXT);
 INSERT INTO hr_employees VALUES('A','A','ทีม 1','Staff','FullTime','ยังทำงานอยู่','01/09/2026',''),('B','B','ทีม 2','Staff','FullTime','ยังทำงานอยู่','2026-09-01','');
 CREATE TABLE hr_work_submissions(submission_type TEXT,team TEXT,work_date TEXT,author_email TEXT);
 INSERT INTO hr_work_submissions VALUES('new','ทีม 1','2026-09-01','a@test'),('301','ทีม 2','2026-09-02','b@test'),('new','ทีม 1','2026-10-01','a@test');
 CREATE TABLE hr_attendance_records(employee_id TEXT,record_date TEXT,record_type TEXT,source_type TEXT);
 INSERT INTO hr_attendance_records VALUES('A','2026-09-02','absence','manual');
 CREATE TABLE hr_daily_work_reviews(employee_id TEXT,review_date TEXT,result_status TEXT);
 INSERT INTO hr_daily_work_reviews VALUES('A','2026-09-01','complete'),('B','2026-09-01','none');
 CREATE TABLE hr_daily_work_status_config(id INTEGER,included_statuses TEXT); INSERT INTO hr_daily_work_status_config VALUES(1,'["working"]');
 CREATE TABLE hr_attendance_rules(event_type TEXT,action_value INTEGER,active INTEGER,action_type TEXT); INSERT INTO hr_attendance_rules VALUES('absence',0,1,'limit');
 CREATE TABLE hr_monthly_deposit_results(employee_id TEXT,result_month TEXT,deposit_count INTEGER,result_type TEXT); INSERT INTO hr_monthly_deposit_results VALUES('A','2026-09',0,'red');
 CREATE TABLE hr_payroll_records(employee_id TEXT,payroll_month TEXT,net_salary INTEGER); INSERT INTO hr_payroll_records VALUES('A','2026-09',123),('B','2026-09',456);
 CREATE TABLE hr_employee_advances(id INTEGER,employee_id TEXT); INSERT INTO hr_employee_advances VALUES(1,'A'),(2,'B');
 CREATE TABLE hr_advance_installments(advance_id INTEGER,due_month TEXT,amount INTEGER,status TEXT); INSERT INTO hr_advance_installments VALUES(1,'2026-09',100,'pending'),(2,'2026-09',200,'deducted'),(1,'2026-09',50,'skipped');`);
 const db={prepare(sql){let args=[];const stmt={bind(...values){args=values;return stmt;},all(){return {results:sqlite.prepare(sql).all(...args)};}};return stmt;}};
 const api=load('../db/dashboard.ts',path=>path==='./index'?{getD1:()=>db}:months);
 const user={role:'hr',email:'hr@test',employeeId:null};
 const permissions=['dashboard','attendance','submissions','warnings','payroll','advances'];
 const result=await api.getMonthlyDashboard(user,permissions,'2026-09',new Date('2026-10-02'));
 assert.equal(result.sections.length,6);
 const section=title=>result.sections.find(s=>s.title===title);
 assert.equal(section('การส่งงานเว็บ').recorded,2);
 assert.equal(section('ผลตรวจส่งงานรายวัน').metrics.find(m=>m.label==='ยังไม่ตรวจ').value,57);
 assert.equal(section('ยอดฝากและใบเตือน').metrics.find(m=>m.label==='ยังไม่บันทึกยอดฝาก').value,1);
 assert.equal(section('เงินเดือนที่บันทึกจริง').metrics.find(m=>m.unit==='บาท').value,579);
 assert.equal(section('ยอดผ่อนและเงินเบิกล่วงหน้า').metrics[0].value,300);
 const own=await api.getMonthlyDashboard({role:'employee',email:'A@TEST',employeeId:'A'},permissions,'2026-09',new Date('2026-10-02'));
 assert.equal(own.sections.find(s=>s.menu==='submissions').recorded,1);
 assert.equal(own.sections.find(s=>s.menu==='payroll').metrics.find(m=>m.unit==='บาท').value,123);
 assert.equal(own.sections.find(s=>s.menu==='advances').metrics[0].value,100);
 const denied=await api.getMonthlyDashboard(user,['dashboard'],'2026-09');assert.equal(denied.sections.length,0);assert.equal(denied.followups.length,0);
 const unlinked=await api.getMonthlyDashboard({role:'employee',email:'unknown@test',employeeId:null},permissions,'2026-09'); assert.ok(unlinked.sections.every(s=>s.recorded===0));
 const blank=await api.getMonthlyDashboard(user,permissions,'2026-08',new Date('2026-10-02')); assert.ok(blank.sections.every(s=>s.recorded===0));
});
