import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {test} from 'node:test';
import ts from 'typescript';
test('notifications capture changes atomically, hide self actions, restrict ownership and persist read state',async()=>{
 const sqlite=new DatabaseSync(':memory:');
 sqlite.exec(`CREATE TABLE hr_attendance_records(id INTEGER PRIMARY KEY,employee_id TEXT,record_date TEXT,record_type TEXT,reason TEXT,recorder_email TEXT,recorder_user_id TEXT,source_type TEXT DEFAULT 'manual');
 CREATE TABLE hr_attendance_audit_logs(id INTEGER PRIMARY KEY,attendance_record_id INTEGER,employee_id TEXT,action TEXT,previous_record_date TEXT,new_record_date TEXT,previous_record_type TEXT,new_record_type TEXT,previous_reason TEXT,new_reason TEXT,actor_email TEXT,actor_user_id TEXT,actor_display_name TEXT);
 CREATE TABLE hr_daily_work_review_logs(id INTEGER PRIMARY KEY,employee_id TEXT,review_date TEXT,previous_status TEXT,new_status TEXT,previous_submitted_count INTEGER,new_submitted_count INTEGER,previous_reason TEXT,new_reason TEXT,change_reason TEXT,previous_target_count INTEGER,new_target_count INTEGER,actor_email TEXT,actor_user_id TEXT,actor_display_name TEXT);
 CREATE TABLE hr_employee_daily_work_target_logs(id INTEGER PRIMARY KEY,employee_id TEXT,effective_date TEXT,previous_target INTEGER,new_target INTEGER,actor_email TEXT,actor_name TEXT);`);
 sqlite.exec(readFileSync(new URL('../migrations/1021_personal_notifications.sql',import.meta.url),'utf8'));
 sqlite.exec(`INSERT INTO hr_attendance_records VALUES (1,'B','2026-10-02','late','test','hr@test','hr-id','manual'),(2,'B','2026-10-03','admin','self','b@test','b-id','manual'),(3,'C','2026-10-02','true','private','hr@test','hr-id','manual'),(4,'B','2026-10-02','absence','auto','hr@test','hr-id','work_audit');
 INSERT INTO hr_attendance_audit_logs VALUES (1,1,'B','edit','2026-10-02','2026-10-03','late','true','test','fixed','hr@test','hr-id','HR'),(2,1,'B','delete','2026-10-03',NULL,'true',NULL,'fixed',NULL,'hr@test','hr-id','HR');
 INSERT INTO hr_daily_work_review_logs VALUES (1,'B','2026-10-02','complete','none',1,0,'','absent','corrected',1,1,'hr@test','hr-id','HR');
 INSERT INTO hr_employee_daily_work_target_logs VALUES(1,'B','2026-10-03',2,NULL,'hr@test','HR');`);
 const database={prepare(sql){let args=[];const statement={bind(...values){args=values;return statement;},all(){return {results:sqlite.prepare(sql).all(...args)};},first(){return sqlite.prepare(sql).get(...args)||null;},run(){return sqlite.prepare(sql).run(...args);}};return statement;}};
 const code=ts.transpileModule(readFileSync(new URL('../db/notifications.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;
 const api={};new Function('require','exports',code)(()=>({getD1:()=>database}),api);
 const b={employeeId:'B',email:'B@test',userId:'b-id'};
 let inbox=await api.getNotifications(b);assert.equal(inbox.items.length,5);assert.equal(inbox.unreadCount,5);
 assert.equal(inbox.items.some(n=>n.details.reason==='self'),false);
 assert.equal(inbox.items.find(n=>n.kind==='attendance_change'&&n.action==='edit').details.oldStatus,'late');
 assert.equal(inbox.items.find(n=>n.kind==='employee_target').details.newTarget,null);
 const privateId=(await api.getNotifications({employeeId:'C',email:'c@test',userId:'c-id'})).items[0].id;
 await api.readNotifications(b,{action:'read',id:privateId});assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM hr_notification_reads').get().n,0);
 await api.readNotifications(b,{action:'read',id:inbox.items[0].id});assert.equal((await api.getNotifications(b)).unreadCount,4);
 await api.readNotifications(b,{action:'read_all'});assert.equal((await api.getNotifications(b)).unreadCount,0);
 assert.equal((await api.getNotifications({employeeId:'C',email:'c@test',userId:'c-id'})).unreadCount,1);
 assert.deepEqual((await api.getNotifications({...b,employeeId:null})).items,[]);
 sqlite.exec(`BEGIN;INSERT INTO hr_employee_daily_work_target_logs VALUES(2,'B','2026-11-01',2,3,'hr@test','HR');ROLLBACK;`);
 assert.equal((await api.getNotifications(b)).items.length,5);
 for(let i=10;i<65;i++)sqlite.prepare('INSERT INTO hr_employee_daily_work_target_logs VALUES(?,?,?,?,?,?,?)').run(i,'B','2026-11-01',2,3,'hr@test','HR');
 inbox=await api.getNotifications(b);assert.equal(inbox.items.length,50);assert.equal(inbox.hasMore,true);assert.equal(inbox.unreadCount,55);
 const older=await api.getNotifications(b,inbox.items.at(-1).id);assert.equal(older.items.length,10);assert.equal(older.hasMore,false);
 sqlite.close();
});
