import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {test} from 'node:test';
import ts from 'typescript';
function fixture(){const sql=new DatabaseSync(':memory:');sql.exec(`CREATE TABLE hr_notifications(id INTEGER PRIMARY KEY AUTOINCREMENT,employee_id TEXT,source_kind TEXT,source_id INTEGER,actor_email TEXT,actor_user_id TEXT DEFAULT '',actor_name TEXT,event_date TEXT,action TEXT,details TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(source_kind,source_id));CREATE TABLE hr_notification_reads(user_email TEXT,notification_id INTEGER,read_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(user_email,notification_id));`);sql.exec(readFileSync(new URL('../migrations/1027_system_announcements.sql',import.meta.url),'utf8'));
const db={prepare(query){let args=[];return {bind(...values){args=values;return this;},all(){return {results:sql.prepare(query).all(...args)};},first(){return sql.prepare(query).get(...args)||null;},run(){const r=sql.prepare(query).run(...args);return {meta:{last_row_id:r.lastInsertRowid,changes:r.changes}};}};}};
function module(path,require=()=>({getD1:()=>db})){const out={};new Function('require','exports',ts.transpileModule(readFileSync(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(require,out);return out;}
return {sql,api:module('../db/system-announcements.ts'),notices:module('../db/notifications.ts'),module};}
const hr={email:'hr@test',displayName:'HR',role:'hr',employeeId:'H',userId:'hr'};
const employee={email:'a@test',displayName:'A',role:'employee',employeeId:'A',userId:'a'};
const input={action:'publish',title:'อัปเดต',message:'ทดสอบ',showAt:'2026-10-04T13:00',startsAt:'2026-10-04T14:00',estimatedEndsAt:'2026-10-04T15:00',affectedMenus:['submissions'],pauseWrites:true};
const clock=s=>new Date(s+':00+07:00');
test('schedule boundaries, manual completion, scoped pause, expiry and cancellation',async()=>{const {sql,api}=fixture();const {id}=await api.saveSystemAnnouncement(hr,input,clock('2026-10-04T12:00'));assert.equal((await api.getSystemAnnouncements(employee,false,clock('2026-10-04T12:59'))).items.length,0);assert.equal((await api.getSystemAnnouncements(employee,false,clock('2026-10-04T13:00'))).items[0].phase,'scheduled');assert.equal(await api.pausedAnnouncement(['submissions'],clock('2026-10-04T13:59')),null);assert.ok(await api.pausedAnnouncement(['submissions'],clock('2026-10-04T14:00')));assert.equal(await api.pausedAnnouncement(['checkin'],clock('2026-10-04T14:00')),null);assert.ok(await api.pausedAnnouncement(['submissions'],clock('2026-10-04T16:00')));assert.equal((await api.getSystemAnnouncements(employee,false,clock('2026-10-04T16:00'))).items[0].phase,'deploying');await api.saveSystemAnnouncement(hr,{action:'complete',id},clock('2026-10-04T16:00'));assert.equal(await api.pausedAnnouncement(['submissions'],clock('2026-10-04T16:01')),null);assert.equal((await api.getSystemAnnouncements(employee,false,clock('2026-10-04T16:01'))).items[0].phase,'completed');assert.equal((await api.getSystemAnnouncements(employee,false,clock('2026-10-05T16:01'))).items.length,0);assert.equal(sql.prepare('SELECT COUNT(*) n FROM hr_notifications').get().n,2);await assert.rejects(api.saveSystemAnnouncement(hr,{action:'complete',id}),/ไม่พบ/);await api.saveSystemAnnouncement(hr,{action:'cancel',id});assert.equal((await api.getSystemAnnouncements(employee)).items.length,0);sql.close();});
test('HR authorization, invalid dates, timings and scopes rejected without writes',async()=>{const {sql,api}=fixture();await assert.rejects(api.getSystemAnnouncements(employee,true),/เฉพาะ HR/);await assert.rejects(api.saveSystemAnnouncement(employee,input),/เฉพาะ HR/);for(const change of [{showAt:'2026-02-30T12:00'},{showAt:'2026-10-04T14:01'},{estimatedEndsAt:'2026-10-04T14:00'},{affectedMenus:[]},{affectedMenus:['bogus']}])await assert.rejects(api.saveSystemAnnouncement(hr,{...input,...change},clock('2026-10-04T12:00')));assert.equal(sql.prepare('SELECT COUNT(*) n FROM hr_system_announcements').get().n,0);await api.saveSystemAnnouncement(hr,{...input,affectedMenus:['all'],pauseWrites:false},clock('2026-10-04T12:00'));assert.equal(await api.pausedAnnouncement(['checkin'],clock('2026-10-04T14:00')),null);sql.close();});
test('bell broadcasts to all roles only after show time, independent reads and cancelled notices hidden',async()=>{const {sql,api,notices}=fixture();const {id}=await api.saveSystemAnnouncement(hr,input,clock('2026-10-04T12:00'));sql.prepare("UPDATE hr_system_announcements SET show_at='2099-01-01T00:00:00.000Z',starts_at='2099-01-02T00:00:00.000Z',estimated_ends_at='2099-01-03T00:00:00.000Z' WHERE id=?").run(id);assert.equal((await notices.getNotifications(employee)).unreadCount,0);sql.prepare("UPDATE hr_system_announcements SET show_at='2000-01-01T00:00:00.000Z',starts_at='2000-01-02T00:00:00.000Z',estimated_ends_at='2000-01-03T00:00:00.000Z' WHERE id=?").run(id);assert.equal((await notices.getNotifications(employee)).unreadCount,1);assert.equal((await notices.getNotifications(hr)).unreadCount,1);await notices.readNotifications(employee,{action:'read_all'});assert.equal((await notices.getNotifications(employee)).unreadCount,0);assert.equal((await notices.getNotifications(hr)).unreadCount,1);await api.saveSystemAnnouncement(hr,{action:'complete',id});assert.equal((await notices.getNotifications(employee)).unreadCount,1);await api.saveSystemAnnouncement(hr,{action:'cancel',id});assert.equal((await notices.getNotifications(hr)).unreadCount,0);sql.close();});
test('API pause rejects mutations, keeps reads and announcement management available',async()=>{const {sql,api,module}=fixture();await api.saveSystemAnnouncement(hr,{...input,showAt:'2000-01-01T12:00',startsAt:'2000-01-01T13:00',estimatedEndsAt:'2099-01-01T14:00'},new Date());const auth=module('../app/api/auth.ts',name=>name.includes('system-announcements')?api:name.includes('chatgpt-auth')?{getChatGPTUser:async()=>hr}:{getSystemAccess:async()=>({currentUser:hr,permissions:['submissions','checkin']})});const request=(path,method)=>new Request('https://site.test/api/'+path,{method,headers:{origin:'https://site.test','content-type':'application/json'}});assert.equal((await auth.authorizeApi(request('work-submissions','POST'),{anyPermissions:['submissions']})).response.status,503);assert.equal((await auth.authorizeApi(request('work-submissions','GET'))).ok,true);assert.equal((await auth.authorizeApi(request('checkin','POST'))).ok,true);assert.equal((await auth.authorizeApi(request('system-announcements','POST'),{roles:['hr']})).ok,true);assert.equal((await auth.authorizeApi(request('notifications','POST'))).ok,true);sql.close();});
