import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import { test } from 'node:test';
import ts from 'typescript';

test('submission ownership, team filters, pagination and validation use authenticated identity', async () => {
  const sqlite = new DatabaseSync(':memory:');
  sqlite.exec(`PRAGMA foreign_keys=ON;
    CREATE TABLE hr_employees(id TEXT PRIMARY KEY,nickname TEXT,team TEXT);
    CREATE TABLE hr_system_users(email TEXT,menu_permissions TEXT);
    INSERT INTO hr_employees VALUES('A','เอ','ทีม 1'),('B','บี','ทีม 2');
    INSERT INTO hr_system_users VALUES('a@test','["dashboard","attendance"]'),('b@test','[]'),('c@test','["dashboard","submissions"]');`);
  sqlite.exec(readFileSync(new URL('../migrations/1022_work_submissions.sql', import.meta.url), 'utf8'));
  assert.deepEqual(JSON.parse(sqlite.prepare('SELECT menu_permissions FROM hr_system_users WHERE email=?').get('a@test').menu_permissions), ['dashboard','attendance','submissions']);
  assert.equal(sqlite.prepare('SELECT menu_permissions FROM hr_system_users WHERE email=?').get('b@test').menu_permissions, '[]');
  assert.deepEqual(JSON.parse(sqlite.prepare('SELECT menu_permissions FROM hr_system_users WHERE email=?').get('c@test').menu_permissions), ['dashboard','submissions']);
  sqlite.exec(`CREATE TABLE hr_notifications(id INTEGER PRIMARY KEY AUTOINCREMENT,employee_id TEXT NOT NULL,source_kind TEXT,source_id INTEGER,actor_email TEXT,actor_user_id TEXT,actor_name TEXT,event_date TEXT,action TEXT,details TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(source_kind,source_id));
    CREATE TABLE hr_notification_reads(user_email TEXT,notification_id INTEGER,read_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(user_email,notification_id));`);
  const db = { batch(statements) { sqlite.exec('BEGIN'); try { const results=statements.map(stmt=>stmt.run());sqlite.exec('COMMIT');return results; } catch(error){sqlite.exec('ROLLBACK');throw error;} }, prepare(sql) { let args = []; const stmt = {
    bind(...values) { args = values; return stmt; },
    first() { return sqlite.prepare(sql).get(...args) ?? null; },
    all() { return { results: sqlite.prepare(sql).all(...args) }; },
    run() { const r = sqlite.prepare(sql).run(...args); return { meta: { last_row_id: Number(r.lastInsertRowid) } }; },
  }; return stmt; } };
  const code = ts.transpileModule(readFileSync(new URL('../db/work-submissions.ts', import.meta.url), 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText;
  const api = {}; new Function('require','exports',code)(() => ({ getD1: () => db }), api);
  const realCreate = api.createWorkSubmission;
  const before = new Date('2026-10-03T02:59:59.999Z');
  api.createWorkSubmission = (user,input) => realCreate(user,input,()=>before);
  const a = { email: 'A@test', employeeId: 'A', displayName: 'A',userId:'a-id' };
  const b = { email: 'b@test', employeeId: 'B', displayName: 'B',userId:'b-id' };
  const input = { keyword: ' คีย์ไทย ', website: 'example.com', date: '2026-10-03', parentWebsite: 'parent.com', type: 'new', employeeId: 'B', team: 'ทีม 2', author_email: 'b@test' };
  await api.createWorkSubmission(a, input);
  await api.createWorkSubmission(b, { ...input, type: '301', date: '2026-10-02' });
  const saved = sqlite.prepare('SELECT * FROM hr_work_submissions WHERE id=1').get();
  assert.equal(saved.author_email, 'a@test'); assert.equal(saved.employee_id, 'A'); assert.equal(saved.team, 'ทีม 1'); assert.equal(saved.keyword, 'คีย์ไทย');
  let result = await api.getWorkSubmissions(a, new URLSearchParams());
  assert.equal(result.total, 1); assert.equal(result.items[0].type, 'new'); assert.equal(result.currentUser.team, 'ทีม 1');
  result = await api.getWorkSubmissions(a, new URLSearchParams('scope=team&team=ทีม 2'));
  assert.equal(result.total, 1); assert.equal(result.items[0].type, '301');
  result = await api.getWorkSubmissions(a, new URLSearchParams('scope=all'));
  assert.equal(result.total, 2); assert.equal(result.items[0].date, '2026-10-03');
  for (const bad of [{date:'2026-02-30'}, {date:'not-a-date'}, {type:'other'}, {keyword:''}, {website:'x'.repeat(501)}, {parentWebsite:''}]) {
    await assert.rejects(api.createWorkSubmission(a, { ...input, ...bad }));
  }
  await assert.rejects(api.createWorkSubmission(a, null));
  await assert.rejects(api.getWorkSubmissions(a, new URLSearchParams('scope=team')));
  await assert.rejects(api.getWorkSubmissions(a, new URLSearchParams('scope=wrong')));
  await assert.rejects(api.getWorkSubmissions(a, new URLSearchParams('page=-1')));
  result = await api.getWorkSubmissions(a, new URLSearchParams("scope=team&team=' OR 1=1 --"));
  assert.equal(result.total, 0);
  const unlinked = { email:'hr@test',employeeId:null,displayName:'HR',userId:'hr-id' };
  await api.createWorkSubmission(unlinked, { ...input, type:'301_new' });
  result = await api.getWorkSubmissions(unlinked, new URLSearchParams('scope=team&team=__unassigned__'));
  assert.equal(result.total, 1); assert.equal(result.items[0].type, '301_new');
  for (let i=0; i<100; i++) await api.createWorkSubmission(a, { ...input, keyword:String(i) });
  result = await api.getWorkSubmissions(a, new URLSearchParams());
  assert.equal(result.total, 101); assert.equal(result.items.length, 100);
  const second = await api.getWorkSubmissions(a, new URLSearchParams('page=2'));
  assert.equal(second.items.length, 1); assert.equal(second.items[0].id, 1);
  assert.equal(result.items.some(row=>row.id===second.items[0].id), false);

  const receipt = await api.createWorkSubmission(a,{ items:[input,{...input,type:'301_new'}] });
  assert.equal(receipt.count,2);
  assert.equal(JSON.parse(sqlite.prepare("SELECT details FROM hr_notifications WHERE source_kind='work_submission' AND source_id=?").get(receipt.id).details).count,2);
  const notices={}; const noticeCode=ts.transpileModule(readFileSync(new URL('../db/notifications.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;
  new Function('require','exports',noticeCode)(()=>({getD1:()=>db}),notices);
  let inbox=await notices.getNotifications(a); assert.equal(inbox.items[0].details.count,2);
  assert.equal((await notices.getNotifications({...b,employeeId:'A'})).items.some(n=>n.id===inbox.items[0].id),false);
  await notices.readNotifications(b,{action:'read',id:inbox.items[0].id});
  assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM hr_notification_reads').get().n,0);
  await notices.readNotifications(a,{action:'read',id:inbox.items[0].id});
  assert.equal((await notices.getNotifications(a)).items[0].read,true);
  assert.equal((await notices.getNotifications(unlinked)).items.length,1);
  await notices.readNotifications(unlinked,{action:'read_all'});
  assert.equal((await notices.getNotifications(unlinked)).unreadCount,0);
  const recordCount=()=>sqlite.prepare('SELECT COUNT(*) AS n FROM hr_work_submissions').get().n;
  const beforeCount=recordCount(), beforeNotices=sqlite.prepare('SELECT COUNT(*) AS n FROM hr_notifications').get().n;
  await assert.rejects(api.createWorkSubmission(a,{items:[input,{...input,keyword:''}]})); assert.equal(recordCount(),beforeCount);
  sqlite.exec(`CREATE TRIGGER reject_test_submission BEFORE INSERT ON hr_work_submissions WHEN NEW.website='fail.com' BEGIN SELECT RAISE(ABORT,'test failure');END;`);
  await assert.rejects(api.createWorkSubmission(a,{items:[input,{...input,website:'fail.com'}]}));
  assert.equal(recordCount(),beforeCount);assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM hr_notifications').get().n,beforeNotices);
  sqlite.exec('DROP TRIGGER reject_test_submission');
  for(const time of ['2026-10-03T03:00:00Z','2026-10-03T16:59:59Z']) await assert.rejects(realCreate(a,{...input,date:'2026-10-01'},()=>new Date(time)),/ปิดรับส่งงาน/);
  assert.equal(recordCount(),beforeCount);
  assert.equal(api.submissionWindow(before).canSubmit,true);
  assert.equal(api.submissionWindow(new Date('2026-10-03T03:00:00Z')).canSubmit,false);
  assert.equal(api.submissionWindow(new Date('2026-10-03T17:00:00Z')).canSubmit,true);
  let ticks=0; await assert.rejects(realCreate(a,input,()=>ticks++ ? new Date('2026-10-03T03:00:00Z') : before),/ปิดรับส่งงาน/);
  await assert.rejects(api.createWorkSubmission(a,{items:[]}));
  await assert.rejects(api.createWorkSubmission(a,{items:Array(101).fill(input)}));
  sqlite.exec(`INSERT INTO hr_employees VALUES('C','C','ทีม 10'),('D','กาย','ทีม 2');`);
  await api.createWorkSubmission({email:'c@test',employeeId:'C',displayName:'C'}, {...input,keyword:'=HYPERLINK("x")'});
  await api.createWorkSubmission({email:'d@test',employeeId:'D',displayName:'A'}, {...input,keyword:'comma,"quoted"'});
  const csv=await api.exportWorkSubmissions(a,new URLSearchParams('scope=all'));
  assert.equal(csv.charCodeAt(0),0xFEFF); assert.match(csv,/"ทีม","ชื่อ","คีย์"/);
  assert.equal(csv.indexOf('"ทีม 2"')<csv.indexOf('"ทีม 10"'),true);
  assert.equal(csv.indexOf('"ทีม 2","กาย"')<csv.indexOf('"ทีม 2","บี"'),true);
  assert.ok(csv.includes('"\'=HYPERLINK(""x"")"'));
  assert.ok(csv.includes('"comma,""quoted"""'));
  const teamCSV=await api.exportWorkSubmissions(a,new URLSearchParams('scope=team&team=ทีม 10'));
  assert.equal(teamCSV.includes('"ทีม 2"'),false); assert.equal(teamCSV.split('\r\n').length,2);
  const dated=await api.getWorkSubmissions(a,new URLSearchParams('scope=all&date=2026-10-02'));
  assert.equal(dated.total,1);assert.equal(dated.items[0].type,'301');
  assert.equal((await api.getWorkSubmissions(a,new URLSearchParams('scope=mine&date=2026-10-02'))).total,0);
  const report=await api.workSubmissionReport(a,new URLSearchParams('scope=team&team=ทีม 2&date=2026-10-02'));
  assert.equal(report.length,2);assert.equal(report[1][1],'บี');assert.equal(report[1][4],'2026-10-02');
  const dateCSV=await api.exportWorkSubmissions(a,new URLSearchParams('scope=all&date=2026-10-02'));
  assert.equal(dateCSV.includes('2026-10-03'),false);assert.equal(dateCSV.split('\r\n').length,2);
  const empty=await api.workSubmissionReport(a,new URLSearchParams('scope=all&date=2026-10-04'));
  assert.equal(empty.length,1);
  await assert.rejects(api.getWorkSubmissions(a,new URLSearchParams('date=2026-02-30')));
  await assert.rejects(api.workSubmissionReport(a,new URLSearchParams('date=wrong')));
  const edit={...input,id:1,keyword:'แก้ไขคีย์',website:'edited.com',parentWebsite:'mother.com',date:'2026-10-04',type:'301_new',author_email:'b@test',employeeId:'B',team:'ทีม 2'};
  const noticesBeforeEdit=sqlite.prepare('SELECT COUNT(*) AS n FROM hr_notifications').get().n;
  await api.editWorkSubmission(a,edit,()=>before);
  const updated=sqlite.prepare('SELECT * FROM hr_work_submissions WHERE id=1').get();
  assert.equal(updated.keyword,'แก้ไขคีย์');assert.equal(updated.website,'edited.com');assert.equal(updated.parent_website,'mother.com');assert.equal(updated.work_date,'2026-10-04');assert.equal(updated.submission_type,'301_new');
  assert.equal(updated.author_email,'a@test');assert.equal(updated.employee_id,'A');assert.equal(updated.team,'ทีม 1');
  assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM hr_notifications').get().n,noticesBeforeEdit);
  await assert.rejects(api.editWorkSubmission(b,edit,()=>before),/ไม่มีสิทธิ์/);
  await assert.rejects(api.editWorkSubmission(a,{...edit,id:999999},()=>before),/ไม่พบ/);
  await assert.rejects(api.editWorkSubmission(a,{...edit,id:0},()=>before));
  await assert.rejects(api.editWorkSubmission(a,{...edit,keyword:''},()=>before));
  await assert.rejects(api.editWorkSubmission(a,{...edit,keyword:'late'},()=>new Date('2026-10-03T03:00:00Z')),/ปิดรับ/);
  let editTicks=0;await assert.rejects(api.editWorkSubmission(a,{...edit,keyword:'late'},()=>editTicks++ ? new Date('2026-10-03T03:00:00Z') : before),/ปิดรับ/);
  assert.equal(sqlite.prepare('SELECT keyword FROM hr_work_submissions WHERE id=1').get().keyword,'แก้ไขคีย์');
  const editedList=await api.getWorkSubmissions(a,new URLSearchParams('date=2026-10-04'));
  assert.equal(editedList.items[0].id,1);assert.equal(editedList.items[0].canEdit,true);
  const visibleForeign=await api.getWorkSubmissions(b,new URLSearchParams('scope=all&date=2026-10-04'));
  assert.equal(visibleForeign.items[0].canEdit,false);
  const editedReport=await api.workSubmissionReport(a,new URLSearchParams('date=2026-10-04'));
  assert.equal(editedReport[1][2],'แก้ไขคีย์');assert.equal(editedReport[1][3],'edited.com');
  sqlite.close();
});
