'use client';
import { useCallback, useEffect, useState } from 'react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
export type Announcement = {id:number;title:string;message:string;showAt:string;startsAt:string;estimatedEndsAt:string;affectedMenus:string[];pauseWrites:boolean;status:string;phase:string};
export type AnnouncementData = {items:Announcement[];menus:{value:string;label:string}[];serverNow:string;error?:string};
export function announcementTime(value:string){return new Date(value).toLocaleString('th-TH',{timeZone:'Asia/Bangkok',dateStyle:'medium',timeStyle:'short'});}
const localTime=(offset=0)=>new Date(Date.now()+7*3600000+offset).toISOString().slice(0,16);
export function SystemAnnouncementsPanel(){
 const [data,setData]=useState<AnnouncementData>({items:[],menus:[],serverNow:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState({title:'',message:'',showAt:localTime(),startsAt:localTime(3600000),estimatedEndsAt:localTime(7200000),affectedMenus:['all'],pauseWrites:false});
 const load=useCallback(async()=>{try{const r=await fetch('/api/system-announcements?manage=1',{cache:'no-store'});const d=await r.json() as AnnouncementData;if(!r.ok)throw new Error(d.error||'โหลดประกาศไม่สำเร็จ');setData(d);setError('');}catch(e){setError(e instanceof Error?e.message:'โหลดประกาศไม่สำเร็จ');}},[]);
 useEffect(()=>{const initial=window.setTimeout(()=>void load(),0);const timer=window.setInterval(()=>void load(),30000);return()=>{window.clearTimeout(initial);window.clearInterval(timer);};},[load]);
 async function save(body:Record<string,unknown>){setBusy(true);try{const r=await fetch('/api/system-announcements',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||'บันทึกไม่สำเร็จ');toast.success('บันทึกประกาศแล้ว');await load();window.dispatchEvent(new Event('system-announcements-updated'));}catch(e){toast.error(e instanceof Error?e.message:'บันทึกไม่สำเร็จ');}finally{setBusy(false);}}
 const input='mt-2 w-full rounded-xl border bg-white p-3 text-sm';
 return <div className="space-y-6"><section className="panel p-5"><h2 className="text-lg font-semibold">สร้างประกาศ / รอบอัปเดตระบบ</h2><p className="mt-2 text-sm text-muted-foreground">วันเวลาทั้งหมดเป็นเวลาไทย กระดิ่งและแถบสีเหลืองจะเริ่มแสดงตามเวลาเริ่มประกาศ</p><form className="mt-5 space-y-4" onSubmit={e=>{e.preventDefault();void save({action:'publish',...form});}}>
 <label className="block">หัวข้อ<input required maxLength={150} className={input} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label>
 <label className="block">ข้อความประกาศ<textarea required maxLength={2000} rows={3} className={input} value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></label>
 <div className="grid gap-4 md:grid-cols-3">{([['showAt','เริ่มแสดงประกาศ'],['startsAt','เริ่มอัปเดต'],['estimatedEndsAt','สิ้นสุดโดยประมาณ']] as const).map(([key,label])=><label key={key}>{label}<input type="datetime-local" required className={input} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div>
 <fieldset><legend className="mb-3">ส่วนที่ได้รับผลกระทบ</legend><div className="grid gap-3 sm:grid-cols-3">{data.menus.map(menu=><label key={menu.value} className="flex items-center gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" checked={form.affectedMenus.includes(menu.value)} onChange={e=>setForm({...form,affectedMenus:e.target.checked?menu.value==='all'?['all']:[...form.affectedMenus.filter(x=>x!=='all'),menu.value]:form.affectedMenus.filter(x=>x!==menu.value)})}/>{menu.label}</label>)}</div></fieldset>
 <label className="flex items-start gap-3 rounded-xl bg-amber-50 p-4"><input type="checkbox" className="mt-1" checked={form.pauseWrites} onChange={e=>setForm({...form,pauseWrites:e.target.checked})}/><span>พักการบันทึกในส่วนที่เลือกเมื่อเริ่มอัปเดต<span className="mt-1 block text-sm text-muted-foreground">ยังเปิดดูข้อมูลได้ หากไม่เลือก ผู้ใช้งานจะบันทึกได้ตามปกติ</span></span></label>
 <p className="text-sm text-muted-foreground">เวลาสิ้นสุดเป็นเพียงการประมาณ HR ต้องกด “อัปเดตเสร็จแล้ว” เพื่อจบประกาศและเปิดการบันทึก ระบบจะไม่โหลดหน้าใหม่ให้อัตโนมัติ</p>
 <Button disabled={busy}>เผยแพร่ประกาศ</Button></form>{error&&<p role="alert" className="mt-4 text-rose-600">{error}</p>}</section>
 <section className="panel p-5"><h2 className="mb-4 text-lg font-semibold">ประกาศทั้งหมด</h2><div className="space-y-4">{!data.items.length&&<p className="text-muted-foreground">ยังไม่มีประกาศ</p>}{data.items.map(item=><article key={item.id} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{item.title}</h3><span className="text-sm">{item.status==='completed'?'อัปเดตเสร็จแล้ว':item.status==='cancelled'?'ยกเลิกแล้ว':item.phase==='deploying'?'กำลังอัปเดต':'รออัปเดต'}</span></div><p className="mt-2 whitespace-pre-wrap break-words text-sm">{item.message}</p><p className="mt-2 text-sm">ประกาศ {announcementTime(item.showAt)} · เริ่ม {announcementTime(item.startsAt)} · สิ้นสุดโดยประมาณ {announcementTime(item.estimatedEndsAt)}</p><p className="mt-2 text-sm">{item.affectedMenus.map(x=>data.menus.find(m=>m.value===x)?.label||x).join(', ')} · {item.pauseWrites?'พักบันทึกระหว่างอัปเดต':'ใช้งานได้ตามปกติ'}</p><div className="mt-3 flex flex-wrap gap-2">{item.status==='published'&&<Button disabled={busy} onClick={()=>void save({action:'complete',id:item.id})}>อัปเดตเสร็จแล้ว</Button>}{item.status!=='cancelled'&&<Button variant="outline" disabled={busy} onClick={()=>{if(window.confirm('ยกเลิกและซ่อนประกาศนี้?'))void save({action:'cancel',id:item.id});}}>ยกเลิก / ซ่อนประกาศ</Button>}</div></article>)}</div></section></div>;
}
