'use client';
import { useCallback, useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { announcementTime, type Announcement, type AnnouncementData } from '@/app/system-announcements-panel';
export function SystemAnnouncementBanner({email}:{email:string}){
 const [data,setData]=useState<AnnouncementData>({items:[],menus:[],serverNow:''}),[modal,setModal]=useState<Announcement|null>(null);
 const load=useCallback(async()=>{try{const r=await fetch('/api/system-announcements',{cache:'no-store'});if(!r.ok)return;const d=await r.json() as AnnouncementData;setData(d);const active=d.items.find(x=>x.phase==='deploying'&&!sessionStorage.getItem(`announcement:${email}:${x.id}`));setModal(current=>active ?? (current && d.items.some(x=>x.id===current.id&&x.phase==='deploying') ? current : null));}catch{/* Keep last known notice during an update. */}},[email]);
 useEffect(()=>{const initial=window.setTimeout(()=>void load(),0);const timer=window.setInterval(()=>{if(!document.hidden)void load();},15000);window.addEventListener('focus',load);window.addEventListener('system-announcements-updated',load);return()=>{window.clearTimeout(initial);window.clearInterval(timer);window.removeEventListener('focus',load);window.removeEventListener('system-announcements-updated',load);};},[load]);
 function acknowledge(){if(modal)sessionStorage.setItem(`announcement:${email}:${modal.id}`,'1');setModal(null);}
 return <><div aria-live="polite" className="space-y-2">{data.items.map(item=><section key={item.id} className={`border-b px-5 py-4 ${item.phase==='completed'?'border-emerald-200 bg-emerald-50 text-emerald-900':'border-amber-200 bg-amber-100 text-amber-950'}`}><p className="font-semibold">{item.phase==='completed'?'อัปเดตเสร็จแล้ว':item.phase==='deploying'?'กำลังอัปเดตระบบ':'ประกาศอัปเดตระบบ'} · {item.title}</p><p className="mt-1 whitespace-pre-wrap break-words text-sm">{item.message}</p><p className="mt-1 text-sm">{announcementTime(item.startsAt)} – {announcementTime(item.estimatedEndsAt)} (สิ้นสุดโดยประมาณ) · {item.affectedMenus.map(x=>data.menus.find(m=>m.value===x)?.label||x).join(', ')}</p>{item.phase!=='completed'&&<p className="mt-1 text-sm font-medium">{item.pauseWrites?(item.phase==='deploying'?'พักการบันทึกในส่วนที่ระบุจนกว่า HR จะแจ้งว่าอัปเดตเสร็จแล้ว':'จะพักการบันทึกในส่วนที่ระบุเมื่อถึงเวลาเริ่มอัปเดต'):'ใช้งานและบันทึกได้ตามปกติ'}</p>}{item.phase==='completed'&&<Button className="mt-3" variant="outline" onClick={()=>{if(window.confirm('กรุณาบันทึกข้อมูลที่กำลังกรอกก่อน โหลดเวอร์ชันใหม่ตอนนี้หรือไม่?'))window.location.reload();}}>โหลดเวอร์ชันใหม่</Button>}</section>)}</div><Dialog open={Boolean(modal)} onOpenChange={open=>{if(!open)acknowledge();}}><DialogContent><DialogHeader><DialogTitle>เริ่มอัปเดตระบบแล้ว</DialogTitle><DialogDescription>{modal?.title}</DialogDescription></DialogHeader><p className="whitespace-pre-wrap break-words">{modal?.message}</p><p className="text-sm">{modal?.pauseWrites?'พักการบันทึกในส่วนที่ประกาศ ยังเปิดดูข้อมูลได้':'ใช้งานได้ตามปกติ'}</p><Button onClick={acknowledge}>รับทราบ</Button></DialogContent></Dialog></>;
}
